Sam Adapters for RxJava 2.x
ReactiveX/RxKotlin pull request #114
Opened 2017-04-20 18:53 UTC by thomasnield

This is the SAM adapter implementation WIP for RxKotlin 2.x, initiated from the following discussions by @chris-horner:

https://github.com/ReactiveX/RxKotlin/issues/103
https://github.com/ReactiveX/RxKotlin/pull/109

2017-04-20 18:59 UTC, thomasnield commented
I will look into Travis build errors later. For now, I see we need to create SAM adapters for the following operators, for `ObservableKt`, `FlowableKt`, `MaybeKt`, and `SingleKt` where applicable: 

* `ObservableKt.combineLatest()`
* `ObservableKt.zip()`
* `Observable#zipWith()`
* `Observable#withLatestFrom()`

There might be some needed for `flatMap()` and `concatMap()` overloads as well. Please let me know if I am missing any others.

2017-04-20 23:53 UTC, thomasnield commented
Not quite sure why the Kotlin compiler is not liking `ObservableKt`, `FlowableKt`, `SingleKt`, and `MaybeKt`. It says these are duplicate JVM classes. Looking through the `.class` files and I'm not quite sure if I see any duplicates. I really like those names and want them to work. I'd rather change what they are clashing with. 

![image](https://cloud.githubusercontent.com/assets/7420801/25256967/44f1b1fa-25fa-11e7-92d3-3e7d4861f19a.png)

2017-04-21 00:19 UTC, thomasnield commented
Renamed `ObservableKt` to `Observables`, `FlowableKt` to `Flowables`, etc... to resolve build issues at the moment.

2017-04-24 03:17 UTC, chris-horner commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +    inline fun <T1,T2,R> combineLatest(source1: Flowable<T1>, source2: Flowable<T2>, crossinline combineFunction: (T1, T2) -> R) =
nit: I know people aren't often going to be reading this file, but I feel `combiner` is a nicer name than `combineFunction`.

2017-04-24 13:52 UTC, thomasnield commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +    inline fun <T1,T2,R> combineLatest(source1: Flowable<T1>, source2: Flowable<T2>, crossinline combineFunction: (T1, T2) -> R) =
Okay Ill change that.

2017-04-24 23:32 UTC, chris-horner commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +                    io.reactivex.functions.Function3<T1, T2, T3, R> { t1: T1, t2: T2, t3: T3 -> combiner(t1,t2, t3) })!!
Any particular reason for the fully qualified `Function`s?

2017-04-25 00:43 UTC, thomasnield commented
My compiler struggled if I didn't.

2017-04-25 00:54 UTC, chris-horner commented
Have a look at the methods I've defined that you've copied across. `Function3`, `4, and `5` all work without being fully qualified. Perhaps IntelliJ's not grabbing the correct import for you?

2017-04-28 14:55 UTC, thomasnield commented
I'll follow up this weekend on this.

2017-04-29 00:26 UTC, thomasnield commented
@chris-horner Couldn't figure out the `BiFunction` not inferring correctly, but was able to clean up the others.

2017-04-29 12:20 UTC, stepango requested changes

2017-04-29 12:20 UTC, stepango commented on build.gradle
> +    ext.kotlin_version = '1.1.2'
1.1.2-2 is the latest one

2017-04-29 12:20 UTC, stepango commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +import io.reactivex.functions.*
avoid wildcard imports

2017-04-29 12:20 UTC, stepango commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +package io.reactivex.rxkotlin
code formatting in all file

2017-04-29 12:20 UTC, stepango commented on src/main/kotlin/io/reactivex/rxkotlin/Flowables.kt
> +                    BiFunction<T1, T2, R> { t1, t2 -> combineFunction(t1,t2) })!!
why `!!`?

2017-05-02 00:14 UTC, merged