Zip Pair/Triple
ReactiveX/RxKotlin pull request #125
Opened 2017-05-20 17:26 UTC by stepango

2017-05-23 10:45 UTC, marcinsus commented
As for me, a useful feature. 👍

2017-05-23 10:48 UTC, thomasnield commented
Might want to add a Pair extension for toMap() as well

2017-05-23 13:18 UTC, marcinsus commented
@stepango two things: 
1. This types of method should be also in other method like latestFrom etc.
2. It is very nice to use but for me it is little inconsistent with base rxjava which requires zipper to connect two observable. I am not sure if we change this behaviour some rx users can be little confused.
 
Another way to archive it is create helper method something like:
` private fun <T, U> pairZipper(): (T, U) -> Pair<T, U> = { first: T, second: U ->
        first to second
    }
`

2017-05-24 03:30 UTC, stepango commented
@marcinsus `pairZipper` does not make any sense, you could just use `::Pair` with one of rxKotlin's extension methods if you like

2017-05-24 09:51 UTC, marcinsus commented
@stepango are you sure `::Pair` is possible? I had problem with type inference when i try refactor something like that :
```
 Observable.just(3) .zipWith(Observable.just(""), { a, b -> a to b})
```
Also in my case the most of usage when zip 2 observable is create pair so for me default zipper is ok. I am not sure but maybe default parameter instead method will be ok?

2017-05-25 02:25 UTC, stepango commented
@marcinsus `Observables.zip(Observable.just(1), Observable.just(1), ::Pair)`

2017-05-25 09:52 UTC, marcinsus commented
@stepango yeah, Observables.zip (and similar object method) work without problem but extension method like zipWith method have name conflict with rxjava method and ::Pair does not work.

2017-05-26 02:51 UTC, stepango commented
@marcinsus you are right about `::Pair` looks like a bug that type inference does not work for method references if method has overload with same amount of params https://youtrack.jetbrains.com/issue/KT-18080

2017-06-01 13:30 UTC, thomasnield commented
Is there a `combineLatestWith()` natively with RxJava? I know there is a `withLatestFrom()` which is similar but only triggers from the invoked Observable.

2017-06-15 07:09 UTC, stepango commented
@thomasnield no, there is no `combineLatestWith` and `withLatestFrom` behave differently. I don't think it's necessary to rename `combineLatest` to `combineLatestWith` it could confuse people

2017-06-16 01:27 UTC, thomasnield requested changes
Remove combineLatestWith()

2017-06-16 01:27 UTC, thomasnield commented on src/main/kotlin/io/reactivex/rxkotlin/Observables.kt
> + * Shortcut for [Observable.combineLatest] with two args
I propose removing `combineLatestWith()` since this is not natively available in RxJava.

2017-06-24 14:47 UTC, thomasnield commented
Okay, i see there is a `combineLatest()` already in this library that I must have overlooked. I don't agree with it being there, even if it's name is changed to `combineLatestWith()`. I do think a factory overload for `combineLatestWith` in `Observables` and `Flowables` that yield `Pair` and `Triple` would be great though.

2017-06-24 14:48 UTC, thomasnield commented
And again, the reason is because it does not exist in the original RxJava implementation as an operator, only a factory.

2017-06-24 19:54 UTC, thomasnield commented
I went ahead and cherrypicked the ideas from this PR  to implement following:

```
Observables#zip(): Pair<T1,T2>
Observables#zip(): Triple<T1,T2,T3>
Observables#combineLatest(): Pair<T1,T2>
Observables#combineLatest(): Pair<T1,T2,T3>
Observable.zipWith(): Pair<T1,T2>
Observable.withLatestFrom(): Pair<T1,T2>
```

I'm deprecating `combineLatest()` as an operator, and not going forward with `combineLatestWith()` although that would have been a more sensible name for it. 

Feel free to reopen this PR if I missed anything or you feel strongly about any of the above changes.

2017-06-24 19:54 UTC, closed without merging