added a function for onErrorResumeNext method to resolve ambiguity
ReactiveX/RxKotlin pull request #210
Opened 2019-02-03 06:53 UTC by worldsnas

added a function for onErrorResumeNext to resolve ambiguity and easier use in kotlin

2019-03-11 16:37 UTC, RivuChk requested changes
There might me some unintended formatting changes, commented, please do check them once.

2019-03-11 16:37 UTC, RivuChk commented on src/main/kotlin/io/reactivex/rxkotlin/observable.kt
> +inline fun <T : Any, R : Any> Iterable<Observable<T>>.combineLatest(crossinline combineFunction: (args: List<T>) -> R): Observable<R> = Observable.combineLatest(this) { combineFunction(it.asList().ma
Unintended commit? I prefer the previous formatting otherwise.

2019-03-11 16:37 UTC, RivuChk commented on src/main/kotlin/io/reactivex/rxkotlin/observable.kt
> +inline fun <T : Any, R : Any> Observable<T>.flatMapSequence(crossinline body: (T) -> Sequence<R>): Observable<R> = flatMap { body(it).toObservable() }
Unintended commit? I prefer the previous formatting otherwise.

2019-03-11 16:37 UTC, RivuChk commented on src/main/kotlin/io/reactivex/rxkotlin/observable.kt
> +inline fun <T : Any, R : Any> Iterable<Observable<T>>.zip(crossinline zipFunction: (args: List<T>) -> R): Observable<R> = Observable.zip(this) { zipFunction(it.asList().map { it as T }) }
Unintended commit? I prefer the previous formatting otherwise.

2019-03-19 08:58 UTC, stepango requested changes
Pls don't change the formatting of existing code

2019-03-19 10:20 UTC, worldsnas commented
sorry for the mistake. reverted back the formatting. please let me know if anything else has problems

2020-07-06 07:11 UTC, closed without merging

2020-07-21 15:54 UTC, ubuntudroid commented
Is there a reason this wasn't merged, but deleted instead? @worldsnas @stepango @RivuChk Seems like a useful addition to me.

2020-07-22 07:13 UTC, worldsnas commented
I closed mistakenly,
but this project does seem un-maitained

2020-07-22 08:15 UTC, vpriscan commented
The 2.x version of RxJava and RxKotlin is in maintenance mode and will be supported only through bugfixes. No new features or behavior changes will be accepted or applied.

This PR tries to resolve an ambiguity, which passes as a bugfix.

Unfortunately, it does not resolve the ambiguity, tested it with Kotlin 1.3.40, method call is still ambiguous.
@ubuntudroid @worldsnas